feat: Idp 1990 adeguamento create trx generica
pagopa/idpay-payment pull request #186
Opened 2023-10-18 09:33 UTC by Giuseppe-LaManna

#### Description

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

- Pre-Deploy Test
    - [ ] Unit
    - [ ] Integration (Narrow)
- Post-Deploy Test
    - [ ] Isolated Microservice
    - [ ] Broader Integration
    - [ ] Acceptance
    - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [ ] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-18 12:56 UTC, GiovanaSolorzano requested changes

2023-10-18 12:56 UTC, GiovanaSolorzano commented on src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java
>              payloadBuilderBeanClass = BaseTransactionResponseDTOPerfLoggerPayloadBuilder.class)
Use TransactionResponseDTOPerfLoggerPayloadBuilder.class

2023-10-19 10:56 UTC, frtrinca approved these changes

2023-10-19 11:15 UTC, GiovanaSolorzano approved these changes

2023-10-19 11:15 UTC, merged