feat: [IDP-2302] management payment authorization with etag
pagopa/idpay-payment pull request #249
Opened 2024-02-09 08:21 UTC by Giuseppe-LaManna

#### Description

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

- Pre-Deploy Test
    - [ ] Unit
    - [ ] Integration (Narrow)
- Post-Deploy Test
    - [ ] Isolated Microservice
    - [ ] Broader Integration
    - [ ] Acceptance
    - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [ ] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-09 16:25 UTC, antonioT90 requested changes

2024-02-09 16:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/connector/rest/reward/mapper/RewardCalculatorMapper.java
> +        return AuthPaymentRequestDTO.builder()
this body is totally empty except the rewardCents field!
you could write a common method to call in order to fill the model in both methods...

2024-02-09 16:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java
> +    public void updateTrxWithStatus(String id, String userId, Long reward, List<String> rejectionReasons, Map<String, List<String>> initiativeRejectionReasons, Map<String, Reward> rewards, String cha
you should also accept and save the retrieved  counterVersion

2024-02-09 16:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/service/payment/common/CommonAuthServiceImpl.java
> +            trx.setStatus(SyncTrxStatus.AUTHORIZATION_REQUESTED);
you have to store the status inside the database before to invoke rewardCalculator

2024-02-09 16:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/service/payment/common/CommonAuthServiceImpl.java
this setting should not more executed inside the auth behavior:
trx.setTrxChargeDate(OffsetDateTime.now().truncatedTo(ChronoUnit.MILLIS));

2024-02-09 16:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/service/payment/common/CommonAuthServiceImpl.java
MoreOver, the authorization now should save just the status! The reward now is stored by the preview

2024-02-16 11:38 UTC, petretiandrea commented on src/main/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorRestClient.java
> +                                                           @RequestBody PreAuthPaymentRequestDTO body);
I think we could use a more expressive name. We don't have a real pre-authorization phase, so we could refer to this DTO as a payment request, so `PaymentRequestDTO` I think is more appropriated

2024-02-16 16:12 UTC, merged