feat: Idp 887 refactor notify auth payment queue
pagopa/idpay-payment pull request #43
Opened 2023-05-11 13:18 UTC by sbellezz

… classes and properties, changed queue for authPayment notification and updated test classes

2023-05-11 14:01 UTC, antonioT90 requested changes

2023-05-11 14:01 UTC, antonioT90 commented on helm/values.yaml
> +
remove also KAFKA_TOPIC_NOTIFICATION configuration: it should not more used (maybe you could remove the entire idpay-eventhub-00 block...)

2023-05-11 14:29 UTC, sbellezz commented on src/main/java/it/gov/pagopa/payment/service/qrcode/QRCodeAuthPaymentServiceImpl.java
i need the trx updated before its passed to the _sendAuthPaymentNotification_ method

2023-05-11 14:31 UTC, sbellezz commented on helm/values.yaml
>        KAFKA_TRANSACTION_OUTCOME_CONFIG_SECURITY_PROTOCOL: kafka_security_protocol
should i also remove these 2 properties since they are not used?

2023-05-11 15:38 UTC, antonioT90 requested changes

2023-05-11 16:53 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/service/TransactionNotifierServiceImpl.java
> +                .build();
```suggestion
    public static Message<TransactionInProgress> buildMessage(TransactionInProgress trx, String key) {
        return MessageBuilder.withPayload(trx)
                .setHeader(KafkaHeaders.KEY, key)
                .build();
```

2023-05-12 07:18 UTC, antonioT90 approved these changes

2023-05-12 07:22 UTC, merged